
config {
  type: "view"
}

-- The rest of a SQLX file contains your SELECT statement used to create the table.


SELECT users.id, email, concat(first_name,' -- ',last_name) as name, 
sum(orders.sale_price) as lifetime_revenue, 
count(distinct orders.id) as lifetime_orders,
max(orders.created_at) as last_order_date
from `brendanlooker.thelook.users_vw` users
join `brendanlooker.thelook.order_items_vw` orders on users.id = orders.user_id
group by 1,2,3
